version: '3'
services:
  mysql_master:
    image: mysql:5.7
    env_file:
      - $HOME/project/mysql-cluster/master/mysql_master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - $HOME/project/mysql-cluster/master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - $HOME/project/mysql-cluster/master/data:/var/lib/mysql
      - $HOME/project/mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - overlay

  mysql_slave:
    image: mysql:5.7
    env_file:
      - $HOME/project/mysql-cluster/slave/mysql_slave.env
    container_name: "mysql_slave"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - $HOME/project/mysql-cluster/slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - $HOME/project/mysql-cluster/slave/data:/var/lib/mysql
      - $HOME/project/mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - overlay

  mysql_slave2:
    image: mysql:5.7
    env_file:
      - $HOME/project/mysql-cluster/slave2/mysql_slave.env
    container_name: "mysql_slave2"
    restart: "no"
    ports:
      - 5507:3306
    depends_on:
      - mysql_master
    volumes:
      - $HOME/project/mysql-cluster/slave2/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - $HOME/project/mysql-cluster/slave2/data:/var/lib/mysql
      - $HOME/project/mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - overlay

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    ports:
      - "8082:80"
    restart: always
    networks:
      - overlay
    environment:
      PMA_HOST: mysql_master
      MYSQL_ROOT_PASSWORD: 111
    depends_on:
      - mysql_master

  myphp:
    image: php:7.4-apache 
    build: ./
    restart: always
    volumes:
      - $HOME/project/myproject1:/var/www/html
    ports:
     - "8080:80"
    networks:
      - overlay
    depends_on:
      - mysql_master

networks:
  overlay:

